apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 329447598191.dkr.ecr.ap-south-1.amazonaws.com/taskboard-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: taskboard
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
